# This file is not generated by Stainless and is preserved across codegen runs.
# It holds unit tests for the no-op handling in the hand-written *_update_and_poll
# convenience methods (GCLOUD2-27266).
#
# The Cloud API skips task creation when an update does not change the resource
# (e.g. a tags-only update), returning HTTP 200 with an empty task list. The
# update_and_poll helpers must treat that as a completed no-op — return the
# current resource via get instead of erroring on the missing task.
#
# The tests are self-contained: each drives a respx-mocked Cloud task flow, so
# they run under a plain `pytest` (or `scripts/test`) without the Prism mock.
from __future__ import annotations

from typing import Any, Callable

import httpx
import respx
import pytest

from gcore import Gcore, AsyncGcore

base_url = "http://127.0.0.1:4010"

# Shape mirrors a real FINISHED update_router task captured from the Cloud API.
_TASK: dict[str, Any] = {
    "id": "6465bbb6-6009-4f2c-89e5-4ccffabdf98f",
    "state": "FINISHED",
    "task_type": "update_router",
    "client_id": 3621,
    "user_id": 4585,
    "user_client_id": 3621,
    "project_id": 379987,
    "region_id": 76,
    "detailed_state": None,
    "request_id": "a5700e8820e3f8d6e30d8d814472a0ea",
    "error": None,
    "created_on": "2026-07-01T13:33:36",
    "updated_on": "2026-07-01T13:33:37",
    "finished_on": "2026-07-01T13:33:37",
    "acknowledged_at": None,
    "acknowledged_by": None,
    "job_id": None,
    "schedule_id": None,
    "lifecycle_policy_id": None,
    "created_resources": None,
}


def _make_handler(action_tasks: list[str]) -> Callable[[httpx.Request], httpx.Response]:
    def handler(request: httpx.Request) -> httpx.Response:
        path = request.url.path
        if request.method == "GET" and "/tasks/" in path:
            return httpx.Response(200, json=_TASK)
        if request.method == "GET":
            return httpx.Response(200, json={})
        return httpx.Response(200, json={"tasks": action_tasks})  # the update action

    return handler


# Every update_and_poll method. invoke(client) returns a coroutine on an async
# client, so the same table serves both sync and async tests.
UPDATE_AND_POLL_CASES: list[tuple[str, Callable[[Any], Any]]] = [
    (
        "cloud.file_shares.update_and_poll",
        lambda c: c.cloud.file_shares.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.floating_ips.update_and_poll",
        lambda c: c.cloud.floating_ips.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.inference.deployments.update_and_poll",
        lambda c: c.cloud.inference.deployments.update_and_poll("test", project_id=1),
    ),
    (
        "cloud.k8s.clusters.update_and_poll",
        lambda c: c.cloud.k8s.clusters.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.l7_policies.update_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.update_and_poll(
            "test", project_id=1, region_id=1, action="REDIRECT_PREFIX", redirect_prefix="test"
        ),
    ),
    (
        "cloud.load_balancers.listeners.update_and_poll",
        lambda c: c.cloud.load_balancers.listeners.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.pools.update_and_poll",
        lambda c: c.cloud.load_balancers.pools.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.networks.routers.update_and_poll",
        lambda c: c.cloud.networks.routers.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.security_groups.update_and_poll",
        lambda c: c.cloud.security_groups.update_and_poll("test", project_id=1, region_id=1),
    ),
]

_INVOKES = [c[1] for c in UPDATE_AND_POLL_CASES]
_IDS = [c[0] for c in UPDATE_AND_POLL_CASES]


@pytest.mark.parametrize("invoke", _INVOKES, ids=_IDS)
def test_update_and_poll_noop_sync(invoke: Callable[[Any], Any]) -> None:
    # Empty task list (a no-op update) must succeed, not raise.
    client = Gcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_make_handler([]))
        invoke(client)


@pytest.mark.parametrize("invoke", _INVOKES, ids=_IDS)
async def test_update_and_poll_noop_async(invoke: Callable[[Any], Any]) -> None:
    client = AsyncGcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_make_handler([]))
        await invoke(client)


@pytest.mark.parametrize("invoke", _INVOKES, ids=_IDS)
def test_update_and_poll_with_task_sync(invoke: Callable[[Any], Any]) -> None:
    # Normal path: a task is created and polled to completion.
    client = Gcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_make_handler(["task-1"]))
        invoke(client)


@pytest.mark.parametrize("invoke", _INVOKES, ids=_IDS)
async def test_update_and_poll_with_task_async(invoke: Callable[[Any], Any]) -> None:
    client = AsyncGcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_make_handler(["task-1"]))
        await invoke(client)


def test_update_and_poll_case_count() -> None:
    assert len(UPDATE_AND_POLL_CASES) == 9
