# This file is not generated by Stainless and is preserved across codegen runs.
# It holds unit tests for the hand-written *_and_poll convenience methods that
# were isolated into cloud/*_custom.py mixins.
#
# The tests are self-contained: each drives a respx-mocked Cloud task flow
# (action -> poll task -> get), so they run under a plain `pytest` (or
# `scripts/test`) without needing the Prism/Steady mock server.
from __future__ import annotations

from typing import Any, Callable

import httpx
import respx
import pytest

from gcore import Gcore, AsyncGcore

# respx intercepts the transport, so the host is irrelevant.
base_url = "http://127.0.0.1:4010"

CREATED_ID = "00000000-0000-4000-8000-000000000001"

# Every string field of TaskCreatedResources, so any create_and_poll finds its
# resource. Numeric collections use ints.
_CREATED_RESOURCES: dict[str, Any] = {
    k: [CREATED_ID]
    for k in [
        "ai_clusters",
        "api_keys",
        "caas_containers",
        "clusters",
        "faas_functions",
        "faas_namespaces",
        "file_shares",
        "floatingips",
        "healthmonitors",
        "images",
        "inference_instances",
        "instances",
        "k8s_clusters",
        "k8s_pools",
        "l7polices",
        "l7rules",
        "laas_topic",
        "listeners",
        "loadbalancers",
        "members",
        "networks",
        "pools",
        "ports",
        "postgresql_clusters",
        "registry_registries",
        "registry_users",
        "routers",
        "secrets",
        "security_group_rules",
        "security_groups",
        "servergroups",
        "snapshots",
        "subnets",
        "volumes",
    ]
}
_CREATED_RESOURCES["projects"] = [1]
_CREATED_RESOURCES["ddos_profiles"] = [1]

# Shape mirrors a real FINISHED create_fip task captured from the Cloud API.
_TASK: dict[str, Any] = {
    "id": "50e2042d-761b-4f5a-b5bf-e11031c747b0",
    "state": "FINISHED",
    "task_type": "create_fip",
    "client_id": 3621,
    "user_id": 4585,
    "user_client_id": 3621,
    "project_id": 379987,
    "region_id": 76,
    "detailed_state": None,
    "request_id": "01601532933a3a7e7a71f935befd1dd1",
    "error": None,
    "created_on": "2026-07-01T13:37:14",
    "updated_on": "2026-07-01T13:37:17",
    "finished_on": "2026-07-01T13:37:17",
    "acknowledged_at": None,
    "acknowledged_by": None,
    "job_id": None,
    "schedule_id": None,
    "lifecycle_policy_id": None,
    "created_resources": _CREATED_RESOURCES,
}

# A few create_and_poll methods re-fetch the parent and search a nested
# collection for the just-created child (baremetal servers via list .results,
# pool members via pool.members, security-group rules via .security_group_rules).
# The superset below carries CREATED_ID in each; unrelated resources ignore it.
_RESOURCE: dict[str, Any] = {
    "count": 1,
    "results": [{"id": CREATED_ID}],
    "members": [{"id": CREATED_ID}],
    "security_group_rules": [{"id": CREATED_ID}],
    # instances.images.upload_and_poll re-polls the image until it settles
    # (status == "active" and size); other methods ignore these extra fields.
    "status": "active",
    "size": 10,
}


def _handler(request: httpx.Request) -> httpx.Response:
    path = request.url.path
    if request.method == "GET" and "/tasks/" in path:
        return httpx.Response(200, json=_TASK)
    if request.method == "GET":
        return httpx.Response(200, json=_RESOURCE)
    return httpx.Response(200, json={"tasks": ["task-1"]})  # the action


# (name, invoke) for every *_and_poll method. invoke(client) drives the method
# with dummy args (the mock ignores request bodies); on an async client it
# returns a coroutine, so the same table serves both sync and async tests.
AND_POLL_CASES: list[tuple[str, Callable[[Any], Any]]] = [
    (
        "cloud.baremetal.servers.create_and_poll",
        lambda c: c.cloud.baremetal.servers.create_and_poll(project_id=1, region_id=1, flavor="test", interfaces=[]),
    ),
    (
        "cloud.baremetal.servers.rebuild_and_poll",
        lambda c: c.cloud.baremetal.servers.rebuild_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.file_shares.update_and_poll",
        lambda c: c.cloud.file_shares.update_and_poll("test", project_id=1, region_id=1),
    ),
    ("cloud.floating_ips.create_and_poll", lambda c: c.cloud.floating_ips.create_and_poll(project_id=1, region_id=1)),
    (
        "cloud.floating_ips.delete_and_poll",
        lambda c: c.cloud.floating_ips.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.floating_ips.update_and_poll",
        lambda c: c.cloud.floating_ips.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.gpu_baremetal.clusters.create_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.create_and_poll(
            project_id=1, region_id=1, flavor="test", image_id="test", name="test", servers_count=1, servers_settings={}
        ),
    ),
    (
        "cloud.gpu_baremetal.clusters.delete_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.gpu_baremetal.clusters.images.delete_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.images.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.gpu_baremetal.clusters.images.upload_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.images.upload_and_poll(
            project_id=1, region_id=1, name="test", url="test"
        ),
    ),
    (
        "cloud.gpu_baremetal.clusters.rebuild_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.rebuild_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.gpu_baremetal.clusters.resize_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.resize_and_poll("test", project_id=1, region_id=1, instances_count=1),
    ),
    (
        "cloud.gpu_baremetal.clusters.servers.delete_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.servers.delete_and_poll(
            "test", project_id=1, region_id=1, cluster_id="test"
        ),
    ),
    (
        "cloud.gpu_baremetal.clusters.servers.rebuild_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.servers.rebuild_and_poll(
            "test", project_id=1, region_id=1, cluster_id="test"
        ),
    ),
    (
        "cloud.gpu_baremetal.clusters.servers.replace_and_poll",
        lambda c: c.cloud.gpu_baremetal.clusters.servers.replace_and_poll(
            "test", project_id=1, region_id=1, cluster_id="test"
        ),
    ),
    (
        "cloud.gpu_virtual.clusters.action_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.action_and_poll("test", project_id=1, region_id=1, action="hard_reboot"),
    ),
    (
        "cloud.gpu_virtual.clusters.action_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.action_and_poll(
            "test", project_id=1, region_id=1, action="resize", servers_count=1
        ),
    ),
    (
        "cloud.gpu_virtual.clusters.action_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.action_and_poll("test", project_id=1, region_id=1, action="soft_reboot"),
    ),
    (
        "cloud.gpu_virtual.clusters.action_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.action_and_poll("test", project_id=1, region_id=1, action="start"),
    ),
    (
        "cloud.gpu_virtual.clusters.action_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.action_and_poll("test", project_id=1, region_id=1, action="start"),
    ),
    (
        "cloud.gpu_virtual.clusters.action_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.action_and_poll("test", project_id=1, region_id=1, action="stop"),
    ),
    (
        "cloud.gpu_virtual.clusters.create_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.create_and_poll(
            project_id=1, region_id=1, flavor="test", name="test", servers_count=1, servers_settings={}
        ),
    ),
    (
        "cloud.gpu_virtual.clusters.delete_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.gpu_virtual.clusters.images.delete_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.images.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.gpu_virtual.clusters.images.upload_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.images.upload_and_poll(
            project_id=1, region_id=1, name="test", url="test"
        ),
    ),
    (
        "cloud.gpu_virtual.clusters.servers.delete_and_poll",
        lambda c: c.cloud.gpu_virtual.clusters.servers.delete_and_poll(
            "test", project_id=1, region_id=1, cluster_id="test"
        ),
    ),
    (
        "cloud.inference.deployments.create_and_poll",
        lambda c: c.cloud.inference.deployments.create_and_poll(
            project_id=1, containers=[], flavor_name="test", image="test", listening_port=1, name="test"
        ),
    ),
    (
        "cloud.inference.deployments.delete_and_poll",
        lambda c: c.cloud.inference.deployments.delete_and_poll("test", project_id=1),
    ),
    (
        "cloud.inference.deployments.update_and_poll",
        lambda c: c.cloud.inference.deployments.update_and_poll("test", project_id=1),
    ),
    (
        "cloud.instances.action_and_poll",
        lambda c: c.cloud.instances.action_and_poll("test", project_id=1, region_id=1, action="reboot"),
    ),
    (
        "cloud.instances.action_and_poll",
        lambda c: c.cloud.instances.action_and_poll("test", project_id=1, region_id=1, action="start"),
    ),
    (
        "cloud.instances.action_and_poll",
        lambda c: c.cloud.instances.action_and_poll("test", project_id=1, region_id=1, action="start"),
    ),
    (
        "cloud.instances.add_to_placement_group_and_poll",
        lambda c: c.cloud.instances.add_to_placement_group_and_poll(
            "test", project_id=1, region_id=1, servergroup_id="test"
        ),
    ),
    (
        "cloud.instances.create_and_poll",
        lambda c: c.cloud.instances.create_and_poll(
            project_id=1, region_id=1, flavor="test", interfaces=[], volumes=[]
        ),
    ),
    ("cloud.instances.delete_and_poll", lambda c: c.cloud.instances.delete_and_poll("test", project_id=1, region_id=1)),
    (
        "cloud.instances.images.create_from_volume_and_poll",
        lambda c: c.cloud.instances.images.create_from_volume_and_poll(
            project_id=1, region_id=1, name="test", volume_id="test"
        ),
    ),
    (
        "cloud.instances.images.delete_and_poll",
        lambda c: c.cloud.instances.images.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.instances.images.upload_and_poll",
        lambda c: c.cloud.instances.images.upload_and_poll(project_id=1, region_id=1, name="test", url="test"),
    ),
    (
        "cloud.instances.interfaces.attach_and_poll",
        lambda c: c.cloud.instances.interfaces.attach_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.instances.interfaces.attach_and_poll",
        lambda c: c.cloud.instances.interfaces.attach_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.instances.interfaces.attach_and_poll",
        lambda c: c.cloud.instances.interfaces.attach_and_poll("test", project_id=1, region_id=1, network_id="test"),
    ),
    (
        "cloud.instances.interfaces.attach_and_poll",
        lambda c: c.cloud.instances.interfaces.attach_and_poll("test", project_id=1, region_id=1, port_id="test"),
    ),
    (
        "cloud.instances.interfaces.attach_and_poll",
        lambda c: c.cloud.instances.interfaces.attach_and_poll("test", project_id=1, region_id=1, subnet_id="test"),
    ),
    (
        "cloud.instances.interfaces.detach_and_poll",
        lambda c: c.cloud.instances.interfaces.detach_and_poll(
            "test", project_id=1, region_id=1, ip_address="test", port_id="test"
        ),
    ),
    (
        "cloud.instances.remove_from_placement_group_and_poll",
        lambda c: c.cloud.instances.remove_from_placement_group_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.instances.resize_and_poll",
        lambda c: c.cloud.instances.resize_and_poll("test", project_id=1, region_id=1, flavor_id="test"),
    ),
    (
        "cloud.k8s.clusters.create_and_poll",
        lambda c: c.cloud.k8s.clusters.create_and_poll(
            project_id=1, region_id=1, keypair="test", name="test", pools=[], version="test"
        ),
    ),
    (
        "cloud.k8s.clusters.delete_and_poll",
        lambda c: c.cloud.k8s.clusters.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.k8s.clusters.pools.create_and_poll",
        lambda c: c.cloud.k8s.clusters.pools.create_and_poll(
            "test", project_id=1, region_id=1, flavor_id="test", min_node_count=1, name="test"
        ),
    ),
    (
        "cloud.k8s.clusters.pools.delete_and_poll",
        lambda c: c.cloud.k8s.clusters.pools.delete_and_poll("test", project_id=1, region_id=1, cluster_name="test"),
    ),
    (
        "cloud.k8s.clusters.pools.resize_and_poll",
        lambda c: c.cloud.k8s.clusters.pools.resize_and_poll(
            "test", project_id=1, region_id=1, cluster_name="test", node_count=1
        ),
    ),
    (
        "cloud.k8s.clusters.update_and_poll",
        lambda c: c.cloud.k8s.clusters.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.k8s.clusters.upgrade_and_poll",
        lambda c: c.cloud.k8s.clusters.upgrade_and_poll("test", project_id=1, region_id=1, version="test"),
    ),
    (
        "cloud.load_balancers.create_and_poll",
        lambda c: c.cloud.load_balancers.create_and_poll(project_id=1, region_id=1, name="test"),
    ),
    (
        "cloud.load_balancers.delete_and_poll",
        lambda c: c.cloud.load_balancers.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.failover_and_poll",
        lambda c: c.cloud.load_balancers.failover_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.l7_policies.create_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.create_and_poll(
            project_id=1, region_id=1, action="REDIRECT_PREFIX", listener_id="test", redirect_prefix="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.create_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.create_and_poll(
            project_id=1, region_id=1, action="REDIRECT_TO_POOL", listener_id="test", redirect_pool_id="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.create_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.create_and_poll(
            project_id=1, region_id=1, action="REDIRECT_TO_URL", listener_id="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.create_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.create_and_poll(
            project_id=1, region_id=1, action="REDIRECT_TO_URL", listener_id="test", redirect_url="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.create_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.create_and_poll(
            project_id=1, region_id=1, action="REJECT", listener_id="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.delete_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.l7_policies.rules.create_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.rules.create_and_poll(
            "test", project_id=1, region_id=1, compare_type="CONTAINS", type="COOKIE", value="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.rules.delete_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.rules.delete_and_poll(
            "test", project_id=1, region_id=1, l7policy_id="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.rules.replace_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.rules.replace_and_poll(
            "test", project_id=1, region_id=1, l7policy_id="test", compare_type="CONTAINS", type="COOKIE", value="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.update_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.update_and_poll(
            "test", project_id=1, region_id=1, action="REDIRECT_PREFIX", redirect_prefix="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.update_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.update_and_poll(
            "test", project_id=1, region_id=1, action="REDIRECT_TO_POOL", redirect_pool_id="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.update_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.update_and_poll(
            "test", project_id=1, region_id=1, action="REDIRECT_TO_URL"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.update_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.update_and_poll(
            "test", project_id=1, region_id=1, action="REDIRECT_TO_URL", redirect_url="test"
        ),
    ),
    (
        "cloud.load_balancers.l7_policies.update_and_poll",
        lambda c: c.cloud.load_balancers.l7_policies.update_and_poll(
            "test", project_id=1, region_id=1, action="REJECT"
        ),
    ),
    (
        "cloud.load_balancers.listeners.create_and_poll",
        lambda c: c.cloud.load_balancers.listeners.create_and_poll(
            project_id=1, region_id=1, load_balancer_id="test", name="test", protocol="test", protocol_port=1
        ),
    ),
    (
        "cloud.load_balancers.listeners.delete_and_poll",
        lambda c: c.cloud.load_balancers.listeners.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.listeners.update_and_poll",
        lambda c: c.cloud.load_balancers.listeners.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.pools.create_and_poll",
        lambda c: c.cloud.load_balancers.pools.create_and_poll(
            project_id=1, region_id=1, lb_algorithm="ROUND_ROBIN", name="test", protocol="HTTP"
        ),
    ),
    (
        "cloud.load_balancers.pools.delete_and_poll",
        lambda c: c.cloud.load_balancers.pools.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.pools.update_and_poll",
        lambda c: c.cloud.load_balancers.pools.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.load_balancers.resize_and_poll",
        lambda c: c.cloud.load_balancers.resize_and_poll("test", project_id=1, region_id=1, flavor="test"),
    ),
    (
        "cloud.networks.create_and_poll",
        lambda c: c.cloud.networks.create_and_poll(project_id=1, region_id=1, name="test"),
    ),
    ("cloud.networks.delete_and_poll", lambda c: c.cloud.networks.delete_and_poll("test", project_id=1, region_id=1)),
    (
        "cloud.networks.routers.update_and_poll",
        lambda c: c.cloud.networks.routers.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.networks.subnets.create_and_poll",
        lambda c: c.cloud.networks.subnets.create_and_poll(
            project_id=1, region_id=1, cidr="test", name="test", network_id="test"
        ),
    ),
    (
        "cloud.reserved_fixed_ips.create_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.create_and_poll(
            project_id=1, region_id=1, ip_address="test", network_id="test", type="ip_address"
        ),
    ),
    (
        "cloud.reserved_fixed_ips.create_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.create_and_poll(
            project_id=1, region_id=1, network_id="test", type="any_subnet"
        ),
    ),
    (
        "cloud.reserved_fixed_ips.create_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.create_and_poll(project_id=1, region_id=1, port_id="test", type="port"),
    ),
    (
        "cloud.reserved_fixed_ips.create_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.create_and_poll(
            project_id=1, region_id=1, subnet_id="test", type="subnet"
        ),
    ),
    (
        "cloud.reserved_fixed_ips.create_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.create_and_poll(project_id=1, region_id=1, type="external"),
    ),
    (
        "cloud.reserved_fixed_ips.create_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.create_and_poll(project_id=1, region_id=1, type="external"),
    ),
    (
        "cloud.reserved_fixed_ips.delete_and_poll",
        lambda c: c.cloud.reserved_fixed_ips.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.secrets.upload_tls_certificate_and_poll",
        lambda c: c.cloud.secrets.upload_tls_certificate_and_poll(project_id=1, region_id=1, name="test", payload={}),
    ),
    (
        "cloud.security_groups.create_and_poll",
        lambda c: c.cloud.security_groups.create_and_poll(project_id=1, region_id=1, name="test"),
    ),
    (
        "cloud.security_groups.rules.create_and_poll",
        lambda c: c.cloud.security_groups.rules.create_and_poll("test", project_id=1, region_id=1, direction="egress"),
    ),
    (
        "cloud.security_groups.rules.delete_and_poll",
        lambda c: c.cloud.security_groups.rules.delete_and_poll("test", project_id=1, region_id=1, group_id="test"),
    ),
    (
        "cloud.security_groups.update_and_poll",
        lambda c: c.cloud.security_groups.update_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.volume_snapshots.create_and_poll",
        lambda c: c.cloud.volume_snapshots.create_and_poll(project_id=1, region_id=1, name="test", volume_id="test"),
    ),
    (
        "cloud.volume_snapshots.delete_and_poll",
        lambda c: c.cloud.volume_snapshots.delete_and_poll("test", project_id=1, region_id=1),
    ),
    (
        "cloud.volumes.attach_to_instance_and_poll",
        lambda c: c.cloud.volumes.attach_to_instance_and_poll("test", project_id=1, region_id=1, instance_id="test"),
    ),
    (
        "cloud.volumes.create_and_poll",
        lambda c: c.cloud.volumes.create_and_poll(project_id=1, region_id=1, name="test", size=1, source="new-volume"),
    ),
    (
        "cloud.volumes.create_and_poll",
        lambda c: c.cloud.volumes.create_and_poll(project_id=1, region_id=1, name="test", size=1, source="new-volume"),
    ),
    (
        "cloud.volumes.create_and_poll",
        lambda c: c.cloud.volumes.create_and_poll(project_id=1, region_id=1, name="test", size=1, source="new-volume"),
    ),
    (
        "cloud.volumes.create_and_poll",
        lambda c: c.cloud.volumes.create_and_poll(project_id=1, region_id=1, name="test", size=1, source="new-volume"),
    ),
    ("cloud.volumes.delete_and_poll", lambda c: c.cloud.volumes.delete_and_poll("test", project_id=1, region_id=1)),
    (
        "cloud.volumes.detach_from_instance_and_poll",
        lambda c: c.cloud.volumes.detach_from_instance_and_poll("test", project_id=1, region_id=1, instance_id="test"),
    ),
    (
        "cloud.volumes.resize_and_poll",
        lambda c: c.cloud.volumes.resize_and_poll("test", project_id=1, region_id=1, size=1),
    ),
]


_IDS = [c[0] for c in AND_POLL_CASES]

# *_and_poll helpers that delegate to a base method the API has deprecated;
# calling them emits DeprecationWarning (same as the base method itself).
_DEPRECATED_CASE_IDS = {
    "cloud.gpu_baremetal.clusters.rebuild_and_poll",
    "cloud.gpu_baremetal.clusters.servers.rebuild_and_poll",
}


@pytest.mark.parametrize(("case_id", "invoke"), AND_POLL_CASES, ids=_IDS)
def test_and_poll_sync(case_id: str, invoke: Callable[[Any], Any]) -> None:
    client = Gcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_handler)
        if case_id in _DEPRECATED_CASE_IDS:
            with pytest.warns(DeprecationWarning):
                invoke(client)  # must not raise
        else:
            invoke(client)  # must not raise


@pytest.mark.parametrize(("case_id", "invoke"), AND_POLL_CASES, ids=_IDS)
async def test_and_poll_async(case_id: str, invoke: Callable[[Any], Any]) -> None:
    client = AsyncGcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_handler)
        if case_id in _DEPRECATED_CASE_IDS:
            with pytest.warns(DeprecationWarning):
                await invoke(client)  # must not raise
        else:
            await invoke(client)  # must not raise


def test_and_poll_case_count() -> None:
    # Canary: if codegen adds/removes an *_and_poll method, keep the table in sync.
    assert len(AND_POLL_CASES) == 103


def test_create_and_poll_requires_task() -> None:
    client = Gcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(method="POST").mock(return_value=httpx.Response(200, json={"tasks": []}))
        with pytest.raises(ValueError):
            client.cloud.floating_ips.create_and_poll(project_id=1, region_id=1)


def test_tasks_poll_finished() -> None:
    client = Gcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(side_effect=_handler)
        task = client.cloud.tasks.poll(task_id="task-1")
        assert task.state == "FINISHED"


def test_tasks_poll_error() -> None:
    client = Gcore(base_url=base_url, api_key="test", _strict_response_validation=False)
    errored = dict(_TASK, state="ERROR", error="boom")
    with respx.mock(base_url=base_url) as router:
        router.route(url__regex=r".+").mock(return_value=httpx.Response(200, json=errored))
        with pytest.raises(ValueError, match="boom"):
            client.cloud.tasks.poll(task_id="task-1")
